# Generated by Django 3.2.25 on 2025-05-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eage', models.IntegerField()),
                ('mail', models.CharField(max_length=100)),
                ('ephno', models.CharField(max_length=50)),
                ('esal', models.IntegerField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
